[package]
name = "os"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
riscv = { git = "https://github.com/rcore-os/riscv", features = ["inline-asm"] }

# [profile.release]
# debug = true
